### ISSUE TITLE
Bank Management System using C

### ISSUE THREAD

**Issue by Kritika30032002** [Rancho2002/C-projects#13]
Can I contribute this?

It will includes :-

open_account, 
deposit,
withdraw,
show_balance, 
show_all, 
modify_account, 
close_account

**Along with the password security**

**Comment by Rancho2002** [comment]
Sure!

**Comment by Rancho2002** [comment]
Sure!

**Comment by Rancho2002** [comment]
completed as #21

**Comment by Kritika30032002** [comment]
also Add a label #hacktoberfest-accepted to it
